class initialization
initialize

	Digits := {
		          { true. true. true. false. true. true. true }. "0"
		          { false. false. true. false. false. true. false }. "1"
		          { true. false. true. true. true. false. true }. "2"
		          { true. false. true. true. false. true. true }. "3"
		          { false. true. true. true. false. true. false }. "4"
		          { true. true. false. true. false. true. true }. "5"
		          { true. true. false. true. true. true. true }. "6"
		          { true. false. true. false. false. true. false }. "7"
		          { true. true. true. true. true. true. true }. "8"
		          { true. true. true. true. false. true. true } "9"}