"
I am an ICStepSequencer. I am used to edit Sequencers inside a Performance in a Time Unit Box System
https://en.wikipedia.org/wiki/Time_unit_box_system
I can contain many ICStepSequencerRows each one of them is connected to a key(hence a Sequencer in the uique instance of the Performance class).

"
Class {
	#name : 'ICStepSequencer',
	#superclass : 'BlElement',
	#category : 'CoypuIDE-stepSequencer',
	#package : 'CoypuIDE',
	#tag : 'stepSequencer'
}
